package io.marktone.services

import io.marktone.settings.MarkToneProfile
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class MarkdownRuleComposerTest {

    private val tokens = linkedMapOf(
        "--mt-font-family" to "\"JetBrains Mono\", sans-serif",
        "--mt-font-size" to "14px",
        "--mt-bg" to "#1e1e1e",
        "--mt-fg" to "#d4d4d4",
        "--mt-muted" to "#6a9955",
        "--mt-link" to "#4ea1ff",
        "--mt-border" to "#3a3a3a",
        "--mt-selection" to "#264f78",
        "--mt-code-bg" to "#2a2d2e",
        "--mt-code-fg" to "#ce9178",
        "--mt-keyword" to "#569cd6",
        "--mt-string" to "#ce9178",
        "--mt-accent" to "#b5cea8",
        "--mt-function" to "#dcdcaa",
    )

    private val composer = MarkdownRuleComposer()

    // --- Root block and token embedding ---

    @Test
    fun outputContainsRootBlock() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ":root")
    }

    @Test
    fun rootBlockContainsAllTokenVariables() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        tokens.forEach { (key, value) ->
            assertContains(css, "$key: $value;", message = "Missing token: $key")
        }
    }

    @Test
    fun outputContainsGeneratedByComment() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "Generated by MarkTone")
    }

    // --- Core CSS selectors ---

    @Test
    fun containsBodySelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "html, body")
    }

    @Test
    fun bodyUsesThemeTokens() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "background: var(--mt-bg)")
        assertContains(css, "color: var(--mt-fg)")
        assertContains(css, "font-family: var(--mt-font-family)")
        assertContains(css, "font-size: var(--mt-font-size)")
    }

    @Test
    fun containsHeadingSelectors() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "h1, h2, h3, h4, h5, h6")
        assertContains(css, "h1 {")
        assertContains(css, "h2 {")
        assertContains(css, "h3 {")
    }

    @Test
    fun containsParagraphAndListSelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "p, li")
    }

    @Test
    fun containsLinkSelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "a {")
        assertContains(css, "color: var(--mt-link)")
    }

    @Test
    fun containsBlockquoteSelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "blockquote")
        assertContains(css, "border-left:")
    }

    @Test
    fun containsInlineCodeSelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "code {")
        assertContains(css, "background: var(--mt-code-inline-bg)")
    }

    @Test
    fun containsCodeBlockSelectors() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "pre {")
        assertContains(css, "pre code {")
    }

    @Test
    fun preCodeHasTransparentBackground() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "pre code")
        assertContains(css, "background: transparent")
    }

    @Test
    fun containsTableSelectors() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "table {")
        assertContains(css, "th {")
        assertContains(css, "td {")
        assertContains(css, "border-collapse: collapse")
    }

    @Test
    fun containsHorizontalRuleSelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "hr {")
    }

    @Test
    fun containsBoldSelector() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "strong, b")
    }

    // --- Expressive profile specifics ---

    @Test
    fun expressiveUsesWiderLineHeight() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-line-height: 1.75")
    }

    @Test
    fun expressiveUsesLargerHeadingScale() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-heading-scale: 1.12")
    }

    @Test
    fun expressiveUsesSemanticHeadingColor() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-heading-color: var(--mt-keyword)")
    }

    @Test
    fun expressiveUsesBoldKeywordColor() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-bold-color: var(--mt-keyword)")
    }

    @Test
    fun expressiveUsesStringColorForCode() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-code-color: var(--mt-string)")
    }

    @Test
    fun expressiveUsesAccentForBlockquote() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-blockquote-accent: var(--mt-accent)")
    }

    @Test
    fun expressiveUsesLargerParagraphMargin() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-paragraph-margin: 1em")
    }

    @Test
    fun expressiveUsesLargerBlockPadding() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-block-padding: 14px")
    }

    @Test
    fun expressiveTableHeaderUsesKeywordColor() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-th-color: var(--mt-keyword)")
    }

    // --- Minimal profile specifics ---

    @Test
    fun minimalUsesCompactLineHeight() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-line-height: 1.45")
    }

    @Test
    fun minimalUsesNoHeadingScale() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-heading-scale: 1.00")
    }

    @Test
    fun minimalUsesForegroundHeadingColor() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-heading-color: var(--mt-fg)")
    }

    @Test
    fun minimalUsesForegroundBoldColor() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-bold-color: var(--mt-fg)")
    }

    @Test
    fun minimalUsesForegroundForCode() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-code-color: var(--mt-fg)")
    }

    @Test
    fun minimalUsesBorderForBlockquote() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-blockquote-accent: var(--mt-border)")
    }

    @Test
    fun minimalUsesCompactParagraphMargin() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-paragraph-margin: 0.5em")
    }

    @Test
    fun minimalUsesCompactBlockPadding() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-block-padding: 8px")
    }

    @Test
    fun minimalTableHeaderUsesForegroundColor() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, "--mt-th-color: var(--mt-fg)")
    }

    // --- Syntax highlighting: Expressive ---

    @Test
    fun expressiveHighlightsKeywords() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ".hljs-keyword")
        assertContains(css, ".hljs-built_in")
        assertContains(css, ".hljs-literal")
    }

    @Test
    fun expressiveHighlightsStrings() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ".hljs-string")
        assertContains(css, ".hljs-regexp")
        assertContains(css, ".hljs-attr")
        assertContains(css, ".hljs-symbol")
    }

    @Test
    fun expressiveHighlightsNumbers() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ".hljs-number")
    }

    @Test
    fun expressiveHighlightsComments() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ".hljs-comment")
        assertContains(css, ".hljs-meta")
    }

    @Test
    fun expressiveHighlightsFunctions() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ".hljs-title")
        assertContains(css, ".hljs-title.function_")
    }

    @Test
    fun expressiveHighlightsTypes() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, ".hljs-type")
    }

    @Test
    fun expressiveCommentsAreItalic() {
        val css = composer.compose(tokens, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "font-style: italic")
    }

    // --- Syntax highlighting: Minimal ---

    @Test
    fun minimalHighlightsKeywords() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, ".hljs-keyword")
    }

    @Test
    fun minimalHighlightsComments() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertContains(css, ".hljs-comment")
    }

    @Test
    fun minimalDoesNotHighlightStrings() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertFalse(css.contains(".hljs-string"))
    }

    @Test
    fun minimalDoesNotHighlightFunctions() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertFalse(css.contains(".hljs-title"))
    }

    @Test
    fun minimalDoesNotHighlightNumbers() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertFalse(css.contains(".hljs-number"))
    }

    @Test
    fun minimalDoesNotHighlightTypes() {
        val css = composer.compose(tokens, MarkToneProfile.MINIMAL)
        assertFalse(css.contains(".hljs-type"))
    }

    // --- Profile parity: both profiles share core structure ---

    @Test
    fun bothProfilesContainAllCoreSelectors() {
        val coreSelectors = listOf(
            "html, body", "h1, h2, h3, h4, h5, h6", "p, li",
            "strong, b", "a {", "blockquote", "code {", "pre {",
            "pre code", "table {", "th {", "td {", "hr {",
        )
        for (profile in MarkToneProfile.entries) {
            val css = composer.compose(tokens, profile)
            coreSelectors.forEach { selector ->
                assertContains(css, selector, message = "$profile missing selector: $selector")
            }
        }
    }

    @Test
    fun bothProfilesEmbedAllTokens() {
        for (profile in MarkToneProfile.entries) {
            val css = composer.compose(tokens, profile)
            tokens.forEach { (key, value) ->
                assertContains(css, "$key: $value;", message = "$profile missing token: $key")
            }
        }
    }

    @Test
    fun bothProfilesSetLineHeight() {
        for (profile in MarkToneProfile.entries) {
            val css = composer.compose(tokens, profile)
            assertContains(css, "--mt-line-height:", message = "$profile missing line-height")
        }
    }

    // --- Edge case: empty or minimal tokens ---

    @Test
    fun emptyTokensStillProducesValidCssStructure() {
        val css = composer.compose(emptyMap(), MarkToneProfile.MINIMAL)
        assertContains(css, ":root")
        assertContains(css, "html, body")
    }

    @Test
    fun singleTokenIsEmbedded() {
        val singleToken = mapOf("--mt-bg" to "#000000")
        val css = composer.compose(singleToken, MarkToneProfile.EXPRESSIVE)
        assertContains(css, "--mt-bg: #000000;")
    }
}
