package io.marktone.services

import com.intellij.openapi.components.Service
import io.marktone.settings.MarkToneProfile

@Service(Service.Level.APP)
class MarkdownRuleComposer {

    fun compose(tokens: Map<String, String>, profile: MarkToneProfile): String {
        val profileBlock = when (profile) {
            MarkToneProfile.EXACT_MATCH -> """
                --mt-line-height: 1.55;
                --mt-heading-scale: 1.00;
            """.trimIndent()

            MarkToneProfile.READABLE_DOCS -> """
                --mt-line-height: 1.70;
                --mt-heading-scale: 1.08;
            """.trimIndent()
        }

        val cssVars = buildString {
            appendLine(":root {")
            tokens.forEach { (key, value) ->
                appendLine("  $key: $value;")
            }
            profileBlock.lines().forEach { appendLine("  $it") }
            appendLine("}")
        }

        return """
            /* Generated by MarkTone. Manual edits may be overwritten. */
            $cssVars

            html, body {
                background: var(--mt-bg);
                color: var(--mt-fg);
                font-family: var(--mt-font-family);
                font-size: var(--mt-font-size);
                line-height: var(--mt-line-height);
            }

            h1, h2, h3, h4, h5, h6 {
                color: var(--mt-fg);
                line-height: 1.25;
            }

            h1 { font-size: calc(2rem * var(--mt-heading-scale)); }
            h2 { font-size: calc(1.65rem * var(--mt-heading-scale)); }
            h3 { font-size: calc(1.35rem * var(--mt-heading-scale)); }

            p, li, td, th {
                color: var(--mt-fg);
            }

            a {
                color: var(--mt-link);
            }

            blockquote {
                border-left: 3px solid var(--mt-border);
                color: var(--mt-muted);
                padding-left: 12px;
                margin-left: 0;
            }

            code {
                background: var(--mt-code-bg);
                color: var(--mt-code-fg);
                padding: 0.1rem 0.25rem;
                border-radius: 4px;
            }

            pre {
                background: var(--mt-code-bg);
                border: 1px solid var(--mt-border);
                border-radius: 6px;
                padding: 12px;
                overflow: auto;
            }

            pre code {
                padding: 0;
                border-radius: 0;
            }

            table {
                border-collapse: collapse;
            }

            th, td {
                border: 1px solid var(--mt-border);
                padding: 6px 10px;
            }

            hr {
                border: none;
                border-top: 1px solid var(--mt-border);
                margin: 1.5rem 0;
            }
        """.trimIndent()
    }
}
