package io.marktone.services

import com.intellij.openapi.components.Service
import io.marktone.settings.MarkToneProfile

@Service(Service.Level.APP)
class MarkdownRuleComposer {

    fun compose(tokens: Map<String, String>, profile: MarkToneProfile): String {
        val profileBlock = when (profile) {
            MarkToneProfile.MINIMAL -> """
                --mt-line-height: 1.45;
                --mt-heading-scale: 1.00;
                --mt-paragraph-margin: 0.5em;
                --mt-heading-margin-top: 0.8em;
                --mt-heading-margin-bottom: 0.3em;
                --mt-block-padding: 8px;
                --mt-table-padding: 4px 8px;
                --mt-heading-color: var(--mt-fg);
                --mt-bold-color: var(--mt-fg);
                --mt-code-color: var(--mt-fg);
                --mt-code-inline-bg: var(--mt-code-bg);
                --mt-blockquote-accent: var(--mt-border);
                --mt-th-color: var(--mt-fg);
            """.trimIndent()

            MarkToneProfile.EXPRESSIVE -> """
                --mt-line-height: 1.75;
                --mt-heading-scale: 1.12;
                --mt-paragraph-margin: 1em;
                --mt-heading-margin-top: 1.4em;
                --mt-heading-margin-bottom: 0.6em;
                --mt-block-padding: 14px;
                --mt-table-padding: 8px 12px;
                --mt-heading-color: var(--mt-keyword);
                --mt-bold-color: var(--mt-keyword);
                --mt-code-color: var(--mt-string);
                --mt-code-inline-bg: var(--mt-code-bg);
                --mt-blockquote-accent: var(--mt-accent);
                --mt-th-color: var(--mt-keyword);
            """.trimIndent()
        }

        val cssVars = buildString {
            appendLine(":root {")
            tokens.forEach { (key, value) ->
                appendLine("  $key: $value;")
            }
            profileBlock.lines().forEach { appendLine("  $it") }
            appendLine("}")
        }

        return """
            /* Generated by MarkTone. Manual edits may be overwritten. */
            $cssVars

            html, body {
                background: var(--mt-bg);
                color: var(--mt-fg);
                font-family: var(--mt-font-family);
                font-size: var(--mt-font-size);
                line-height: var(--mt-line-height);
            }

            h1, h2, h3, h4, h5, h6 {
                color: var(--mt-heading-color);
                line-height: 1.25;
                margin-top: var(--mt-heading-margin-top);
                margin-bottom: var(--mt-heading-margin-bottom);
            }

            h1 { font-size: calc(2rem * var(--mt-heading-scale)); }
            h2 { font-size: calc(1.65rem * var(--mt-heading-scale)); }
            h3 { font-size: calc(1.35rem * var(--mt-heading-scale)); }

            p, li {
                color: var(--mt-fg);
                margin-top: var(--mt-paragraph-margin);
                margin-bottom: var(--mt-paragraph-margin);
            }

            strong, b {
                color: var(--mt-bold-color);
            }

            a {
                color: var(--mt-link);
            }

            blockquote {
                border-left: 3px solid var(--mt-blockquote-accent);
                color: var(--mt-muted);
                padding-left: var(--mt-block-padding);
                margin-left: 0;
            }

            code {
                background: var(--mt-code-inline-bg);
                color: var(--mt-code-color);
                padding: 0.1rem 0.25rem;
                border-radius: 4px;
            }

            pre {
                background: var(--mt-code-bg);
                border: 1px solid var(--mt-border);
                border-radius: 6px;
                padding: var(--mt-block-padding);
                overflow: auto;
            }

            pre code {
                background: transparent;
                color: var(--mt-code-fg);
                padding: 0;
                border-radius: 0;
            }

            table {
                border-collapse: collapse;
            }

            th {
                border: 1px solid var(--mt-border);
                padding: var(--mt-table-padding);
                color: var(--mt-th-color);
            }

            td {
                border: 1px solid var(--mt-border);
                padding: var(--mt-table-padding);
                color: var(--mt-fg);
            }

            hr {
                border: none;
                border-top: 1px solid var(--mt-border);
                margin: 1.5rem 0;
            }
        """.trimIndent()
    }
}
